Iosxe/show ap dot11 dual band summary
CiscoTestAutomation/genieparser pull request #217
Opened 2020-08-28 04:21 UTC by reustaquio22

Parser for Iosxe/show ap dot11 dual band summary

2020-09-03 14:12 UTC, tahigash requested changes

2020-09-03 15:25 UTC, danielgraziano requested changes

2020-09-03 15:25 UTC, danielgraziano commented on src/genie/libs/parser/iosxe/show_ap.py
> +        show_ap_dot11_dual_band_summary_dict = {}
If we rename this to `ret_dict = {}` it will make later code a lot smaller

2020-09-03 15:25 UTC, danielgraziano commented on src/genie/libs/parser/iosxe/show_ap.py
> +        for line in out:
This for loop can be a lot smaller, please see example:
```
ret_dict = {}

for line in out:

	# aa-test-4800                 64d8.14ec.1120  0     Enabled       Down           20     *1/8 (23 dBm)   Local   All        (6)*
	m = ap_info_capture.match(line)
	if m:
		groups = m.groupdict()
		ap_index += 1
		
		ap_index_dict = ret_dict.setdefault('ap_dot11_dual-band_summary', {}).\
			setdefault(ap_index, {})
		
		ap_index_dict.update('ap_name': groups['ap_name'])
		ap_index_dict.update('ap_mac_address': groups['ap_mac_address'])
		ap_index_dict.update('slot_id': int(groups['slot_id']))
		ap_index_dict.update('admin_state': groups['admin_state'])
		ap_index_dict.update('oper_state': groups['oper_state'])
		ap_index_dict.update('width': int(groups['width']))
		ap_index_dict.update('tx_pwr': groups['tx_pwr'])
		ap_index_dict.update('mode': groups['mode'])
		ap_index_dict.update('subband': groups['subband'])
		ap_index_dict.update('channel': groups['channel'])
		
return ret_dict
```

This also allows us to remove both `ap_info_headers_capture` and `delimiter_capture` regex. We dont have to match any lines we arent actively using.

If you change schema based on @tahigash comment then its also simple as changing:
```
		ap_index_dict = ret_dict.setdefault('ap_dot11_dual-band_summary', {}).\
			setdefault(ap_index, {})
```
to
```
		ap_index_dict = ret_dict.setdefault('ap_dot11_dual-band_summary', {}).\
			setdefault('indexes', {}).setdefault(ap_index, {})
```

2020-09-14 15:53 UTC, danielgraziano commented
Updated comments and merged here: https://github.com/CiscoTestAutomation/genieparser/pull/237

2020-09-14 15:53 UTC, closed without merging