Parser for ios/xe show ap dot11 5ghz channel
CiscoTestAutomation/genieparser pull request #218
Opened 2020-08-28 04:23 UTC by reustaquio22

Parser for ios/xe show ap dot11 5ghz channel

2020-09-02 14:54 UTC, badalsoyantar commented on src/genie/libs/parser/iosxe/show_ap.py
> +import re
Write comment on top of file for all new parsers command added

2020-09-10 18:35 UTC, tahigash requested changes

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "chan_upd_int": 12,
please change to `chan_upd_int_hour` so that easy to know what the unit is.

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "channel_noise": "Enable",
we respect the indentation and have the schema based on it. could you please update like below?
```
    "channel_update_contribution": {
        "noise": "Enable",
        "interference": "Enable",
        "load": "Disable",
        "device_aware": "Disable",
    }

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "chan_width": "80 MHz",
`dca_chan_width` is better? I understand you tried to have short name as much as possible. but better to have keyword and `max` or `min` thing in key name.

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "max_chan_width": 80,
same for key name. `dbs_max_chan_width`

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "chan_energy_min_dbm": -94.0,
same for indentation. 
```
    "channel_energy_levels": {
        "min_db": -94.0,
        "average_dbm": -82.0,
        "max_db": -81.0,
    }

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "chan_dwell_minimum": "4 hours 9 minutes 54 seconds",
same for indentation.
```
    "channel_dwell_times": {
        "min": "4 hours 9 minutes 54 seconds",
        "average": "4 hours 24 minutes 54 seconds",
        "max": "4 hours 26 minutes 35 seconds",
    }

2020-09-10 18:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_ap.py
> +        "allowed_channel_list": "36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128,132,136,140,144,149,153,157,161",
same for indentation.
```
    "11a_5ghz_auto_rf_channel_list": {
        "allowed_channel_list": "36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128,132,136,140,144,149,153,157,161",
        "unused_channel_list": "165",
    }

2020-09-14 21:21 UTC, badalsoyantar commented
Hi @reustaquio22 next week i will merge this PR from my side just incase you did not get time to resolve this. Thanks.

2020-09-19 17:42 UTC, itdependsnetworks commented
Please close, covered in https://github.com/CiscoTestAutomation/genieparser/pull/251/

2020-10-02 22:16 UTC, closed without merging