Iosxe/show cts role based permissions
CiscoTestAutomation/genieparser pull request #219
Opened 2020-08-28 15:41 UTC by reustaquio22

2020-09-03 14:41 UTC, tahigash requested changes

2020-09-03 14:41 UTC, tahigash commented on changelog/undistributed.rst
> +        * show cts role-based permissions
Why twice?
```suggestion
    * Added ShowCtsRoleBasedPermissions
        * show cts role-based permissions
```

2020-09-03 14:41 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +            1: {
I believe this number is index. if so, better to have key name as `indexes` like below:
```
"indexes": {
    1: {
        "policy_name": "default",
        (snip)

2020-09-03 14:41 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +                "policy_groups": {
no issue to have list at leaf of schema. so, can change to below to be simpler?
```
"policy_groups": ['NFS-08', 'ACCESS-01']

2020-09-03 14:43 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +        Permit IP-00
do you know if any chance to have multiple like below? if yes, we might need to consider to update schema for it.
```
IPv4 Role-based permissions default:
        Permit IP-00
        Permit IP-01

2020-09-19 01:37 UTC, itdependsnetworks commented
please close, covered in https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:31 UTC, tahigash commented on changelog/undistributed.rst
> +        * show cts role-based permissions
confirmed in https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:32 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +            1: {
added the same to https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:33 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +        Permit IP-00
please ignore. added the same to https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:35 UTC, tahigash commented on src/genie/libs/parser/iosxe/show_cts.py
> +        remove_lines = ()
added the same to https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:38 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/test_show_cts.py
> +                "policy_groups": {
added the same to https://github.com/CiscoTestAutomation/genieparser/pull/250

2020-09-22 21:38 UTC, tahigash commented
as per request, closed.

2020-09-22 21:38 UTC, closed without merging