IOSXE/show ap tag summary
CiscoTestAutomation/genieparser pull request #311
Opened 2020-10-22 18:57 UTC by robschn

## Description
Adds parser for the command `show ap tag summary`. Closes #138.

## Motivation and Context
Converts raw output of `show ap tag summary` into structured data.

## Impact (If any)
None

## Screenshots:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/13859438/96916759-fe977500-1475-11eb-875b-4f3649e73760.png">

## Checklist:

- [x] I have updated the changelog.
- [x] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2020-10-23 16:02 UTC, badalsoyantar requested changes

2020-10-23 16:36 UTC, robschn commented on src/genie/libs/parser/iosxe/show_ap.py
> +            if ap_number_capture.match(line):
Updated!

2020-10-23 16:36 UTC, robschn commented on src/genie/libs/parser/iosxe/show_ap.py
> +                ap_info_obj.update(group)
Updated!

2020-10-23 18:58 UTC, tahigash requested changes

2020-10-23 18:58 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_expected.py
> +            "misconfigured": False,
can take the value `No` as is.
```
"misconfigured": "No",

2020-10-23 20:05 UTC, robschn commented on src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_expected.py
> +            "misconfigured": False,
Updated!

2020-10-26 15:42 UTC, badalsoyantar approved these changes

2020-10-29 23:59 UTC, tahigash approved these changes

2020-10-29 23:59 UTC, merged