IOSXE/show lisp eid-table vrf {vrf} ipv4 database
CiscoTestAutomation/genieparser pull request #319
Opened 2020-10-27 18:44 UTC by qduk

## Description
IOSXE/show lisp eid-table vrf ipv4 databse

## Motivation and Context
Take unstructured data returned from command and turn it into structured data

## Screenshots:
![Capture](https://user-images.githubusercontent.com/38091261/97347200-6e34a800-185a-11eb-9e7e-110b27f7a303.PNG)

## Checklist:
- [x] I have updated the changelog.
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2020-10-28 15:13 UTC, xiaoxinz-cisco approved these changes
Thanks for your contribution!

2020-10-30 10:04 UTC, tahigash requested changes
reviewed schema and left 2 comment

2020-11-02 20:03 UTC, qduk commented on src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/equal/golden_output_expected.py
> +    "iid": 4100,
Updated

2020-11-02 20:03 UTC, qduk commented on src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/equal/golden_output_expected.py
> +        "10.16.0.0": {
Updated

2020-11-03 18:23 UTC, tahigash approved these changes
thanks for addressing comment. now schema looks good.

2020-11-03 18:23 UTC, merged