IOSXR/Added show mfib platform evpn bucket location
CiscoTestAutomation/genieparser pull request #320
Opened 2020-10-27 20:26 UTC by brennobrenno

Added show mfib platform evpn bucket location to IOSXR.

<img width="1029" alt="Screen Shot 2020-10-27 at 4 14 05 PM" src="https://user-images.githubusercontent.com/31149320/97358047-0d649a00-1871-11eb-9100-b02801067b6b.png">

2020-10-30 13:04 UTC, tahigash requested changes
reviewed schema and left 1 comment

2020-10-30 13:04 UTC, tahigash commented on src/genie/libs/parser/iosxr/tests/test_show_mfib.py
> +                 'stale': False,
let's take `stale`'s value as is.
```suggestion
                 'stale': 'F',
```

2020-10-31 10:22 UTC, tahigash approved these changes
schema looks good now.

2020-11-02 20:57 UTC, choudnik requested changes

2020-11-02 20:57 UTC, choudnik commented on changelog/undistributed/changelog_show_mfib_platform_evpn_bucket_location_20201027195422.rst
> +* Modified show_mfib.py
Please fix the indentation

2020-11-02 20:57 UTC, choudnik commented on src/genie/libs/parser/iosxr/show_mfib.py
> +# Parser for 'show mfib platform evpn bucket location'
show mfib platform evpn bucket location {location}

2020-11-02 20:57 UTC, choudnik commented on src/genie/libs/parser/iosxr/show_mfib.py
> +# Schema for 'show mfib platform evpn bucket location'
show mfib platform evpn bucket location {location}

2020-11-02 20:57 UTC, choudnik commented on src/genie/libs/parser/iosxr/tests/test_show_mfib.py
> +# Unittest for 'show mfib platform evpn bucket location'
show mfib platform evpn bucket location {location}

2020-11-05 01:12 UTC, brennobrenno commented
Added minor changes!

2020-11-09 14:23 UTC, ThomasJRyan approved these changes

2020-11-09 14:24 UTC, ThomasJRyan commented
Looks good. Please fix conflicts and we can merge it in

2020-11-11 10:19 UTC, tahigash commented
@brennobrenno I tried to resolve the conflict for you but I couldn't. There might be glitch on GitHub or I'm missing something. If you cannot resolve the conflict even from your side, please create new PR with same files. we will approve and merge on new PR. sorry for inconvenience.

2020-11-11 10:21 UTC, brennobrenno commented
> @brennobrenno I tried to resolve the conflict for you but I couldn't. There might be glitch on GitHub or I'm missing something. If you cannot resolve the conflict even from your side, please create new PR with same files. we will approve and merge on new PR. sorry for inconvenience.

Sounds good @tahigash , I will try to resolve conflicts soon. Thanks :)!

2020-11-11 10:26 UTC, tahigash commented
> > @brennobrenno I tried to resolve the conflict for you but I couldn't. There might be glitch on GitHub or I'm missing something. If you cannot resolve the conflict even from your side, please create new PR with same files. we will approve and merge on new PR. sorry for inconvenience.
> 
> Sounds good @tahigash , I will try to resolve conflicts soon. Thanks :)!

sorry for many times. my last try resolved conflict and Checks also passed. 

Thanks for contribution and I'm merging this parser.

2020-11-11 10:26 UTC, merged

2020-11-11 10:28 UTC, brennobrenno commented
@tahigash Perfect, thank you!