IOSXE/show cts wireless profile policy {policy}
CiscoTestAutomation/genieparser pull request #325
Opened 2020-11-02 18:58 UTC by qduk

## Description
Parser created for show cts wireless profile policy {policy}

## Motivation and Context
Takes unstructured data returned from command and puts it into structured data

## Screenshots:
![Capture](https://user-images.githubusercontent.com/38091261/97907534-09ba9280-1d0b-11eb-8bff-dfa3f5f0c9f7.PNG)

## Checklist:
- [x] I have updated the changelog.
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2020-11-04 18:11 UTC, badalsoyantar approved these changes

2020-11-04 18:11 UTC, badalsoyantar commented on src/genie/libs/parser/iosxe/show_cts.py
> +                cts_ap_dict.setdefault("policy_name", {} ).update({ current_policy: {} })
continue

2020-11-04 18:12 UTC, badalsoyantar requested changes
Needs schema review

2020-11-04 20:58 UTC, tahigash approved these changes

2020-11-04 20:58 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/equal/golden_output_expected.py
> +expected_output = {
schema looks good

2020-11-05 17:54 UTC, qduk commented on src/genie/libs/parser/iosxe/show_cts.py
> +                cts_ap_dict.setdefault("policy_name", {} ).update({ current_policy: {} })
Updated

2020-11-05 18:15 UTC, badalsoyantar approved these changes

2020-11-07 15:10 UTC, tahigash commented
Thank you for your contribution!

2020-11-07 15:10 UTC, merged