Main master
CiscoTestAutomation/genieparser pull request #327
Opened 2020-11-02 21:49 UTC by choudnik

## Description
https://github.com/CiscoTestAutomation/genieparser/pull/192

## Motivation and Context
Resolve conflicts and merge

## Impact (If any)

## Screenshots:

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [ ] I have added tests to cover my changes (If applicable).
- [ ] All new and existing tests passed.
- [ ] All new code passed compilation.

2020-11-02 21:51 UTC, bastell approved these changes

2020-11-02 21:53 UTC, bastell requested changes
There are some UT failures that need updating

2020-11-02 22:45 UTC, bastell approved these changes
Approved since related UT is passing

2020-11-03 18:17 UTC, choudnik commented
Added tests for ShowLicenseUdi.
Added screenshots of related tests run

2020-11-04 19:46 UTC, closed without merging