Added IOSXE parser 'show switch stack-ports summary'
CiscoTestAutomation/genieparser pull request #359
Opened 2020-12-15 21:53 UTC by smitsialis

## Description
Added IOSXE parser for:
* show switch stack-ports summary

## Motivation and Context
New Parser

## Impact (If any)
N/A

## Screenshots:
![image](https://user-images.githubusercontent.com/42588542/102274798-715f2280-3ef2-11eb-9237-b11c1a702438.png)

## Checklist:

- [x ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x ] I have added tests to cover my changes (If applicable).
- [x ] All new and existing tests passed.
- [ ] All new code passed compilation.

2020-12-16 21:18 UTC, tahigash requested changes
reviewed schema and left comments

2020-12-16 21:18 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowSwitchStackPortsSummary/cli/equal/golden_output1_expected.py
> +expected_output = {
Please add empty test as well. like below one. just folder with empty file.
https://github.com/CiscoTestAutomation/genieparser/tree/master/src/genie/libs/parser/iosxe/tests/ShowAccessLists/cli/empty

2021-01-14 19:34 UTC, xiaoxinz-cisco commented
Hi @smitsialis , a friendly reminder of this PR, thanks.

2021-01-25 17:08 UTC, smitsialis commented
@xiaoxinz-cisco  Hi,  Sorry for the delay.  Requested changes made; all tests passed.  I'm new to this and wonder how to I update the PR?

2021-01-30 15:38 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowSwitchStackPortsSummary/cli/equal/golden_output1_expected.py
> +         "neighbor":"1",
confirmed the update

2021-01-30 15:38 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowSwitchStackPortsSummary/cli/equal/golden_output1_expected.py
> +         "link_changes_count":"1",
confirmed the change

2021-01-30 15:38 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowSwitchStackPortsSummary/cli/equal/golden_output1_expected.py
> +expected_output = {
confirmed the change

2021-01-30 15:59 UTC, tahigash approved these changes
@smitsialis thanks for you updates. schema looks good now and approved. and I fixed conflicts for you.

@xiaoxinz-cisco please review and if ok, please approve and merge.

2021-02-02 16:10 UTC, xiaoxinz-cisco approved these changes

2021-02-02 16:13 UTC, merged