IOSXR - ShowIsisInterface parser showing missing Key Errors
CiscoTestAutomation/genieparser pull request #418
Opened 2021-03-26 15:42 UTC by Tristou27

## Description
This PR aims at fixing the ISIS `ShowIsisInterface` parser which was not correctly handling 2 things:
- CLNS MTU was not recognized when the router return a `str` instead of an int (error situation)
- Protocol State regex result was not correctly applied to the corresponding sections (clns_io / topologies / address_families)

## Motivation and Context
With IOSXR, using the ShowIsisInterafce parser either via "parse" or "learn isis" module is returning missing key error when dealing with CLNS MTU.
The CLNS MTU is theoritically a number and the parser tries to get a number. In some cases where the CLNS protocol is 'Down', the MTU can return a text value which is an error msg.

The PR edit the matching regex to catch a potential `str` instead of an `int`.
If the value is numeric, the `str` is converted to `int` to preserve compatibility with scripts likely waiting for an `int`. If the value is a `str`, I considered that it is an error message and return -1 for MTU, still as an `int`.

Also, when adding a case to the dedicated unittest to match this modification, I discovered that the `protocol_state` field is badly handled and was not reflected into `address-families` and `topologies` blocks. This has been corrected.

Unittest has been updated consequently to reflect all of those change, unittest are good.

## Impact (If any)
No impact in my opinion

## Screenshots:
```
# ttr @ nietb4 in ~/genieparser/tests on git:isisparser_clns_mtu_iosxr o [16:21:35] 
$ python -m unittest -v 
(...)
----------------------------------------------------------------------
Ran 1521 tests in 32.931s

OK
```

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [ ] All new code passed compilation.

2021-04-01 12:55 UTC, kazemy approved these changes

2021-04-12 22:07 UTC, LukasMcClelland requested changes
Thank you for contributing! Left a few comments

2021-04-13 08:25 UTC, Tristou27 commented on changelog/2021/MARCH.rst
> +        * Correctly handles the 'protocol_state' field under each AF / Topology
Yeah sure, I did forget about that convention. It has been renamed now.

2021-04-13 08:27 UTC, Tristou27 commented on src/genie/libs/parser/iosxr/show_isis.py
> +                topology_falg = False
It has been corrected.

2021-04-13 20:45 UTC, LukasMcClelland commented on changelog/2021/MARCH.rst
> +        * Correctly handles the 'protocol_state' field under each AF / Topology
Confirmed the change

2021-04-13 20:45 UTC, LukasMcClelland commented on src/genie/libs/parser/iosxr/show_isis.py
> +                topology_falg = False
Thank you!

2021-04-13 20:46 UTC, LukasMcClelland approved these changes

2021-04-13 20:46 UTC, LukasMcClelland commented
Approved. Merge away!

2021-04-16 16:22 UTC, LukasMcClelland commented
Decided to marge for you, before any merge conflicts pop up!

2021-04-16 16:22 UTC, merged

2021-04-16 17:45 UTC, Tristou27 commented
Oh thanks :) I did not know I had the correct permissions to merge it myself. Will do it next time !