Update show_cts.py
CiscoTestAutomation/genieparser pull request #520
Opened 2021-08-31 06:03 UTC by komurzak-cisco

updated 'show cts role-based permissions' parser to work on actual output

## Description
This PR fixes a bug when code is trying to access to 'indexes' key of an empty dictionary and was giving error.

## Motivation and Context
Show cts role-based permissions parses was giving error when trying to parse this cli output:
```
IPv4 Role-based permissions from group Invalid to group Invalid:
        Permit IP-00
RBACL Monitor All for Dynamic Policies : FALSE
RBACL Monitor All for Configured Policies : FALSE

```
This PR will fix parsing output of show cts role-based permissions when there are no policies present.
## Impact (If any)
No negative impact

## Screenshots:

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [ ] I have added tests to cover my changes (If applicable).
- [ ] All new and existing tests passed.
- [ ] All new code passed compilation.

2021-09-02 10:48 UTC, domachad requested changes
Thank you four your contribution, @komurzak-cisco!
Can you please add a unit test that supports this change?

2021-09-02 10:48 UTC, domachad commented on changelog/2021/changelog_komurzak_iosxe_show_cts_20210830.rst
> +
Please remove blank lines

2021-09-03 04:52 UTC, komurzak-cisco commented on changelog/2021/changelog_komurzak_iosxe_show_cts_20210830.rst
> +
removed

2021-09-03 04:54 UTC, komurzak-cisco commented
@domachad, unit test added, blank lines removed

2021-09-04 01:51 UTC, tahigash requested changes
reviewed and left comments

2021-09-04 01:51 UTC, tahigash commented on src/genie/libs/parser/iosxe/show_cts.py
> +            Optional(int): {
what kind of output will we see this as Optional?

2021-09-04 01:51 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowCtsRoleBasedPermissions/cli/equal/sample_output_expected.py
> +    "indexes": {
based on the change, below can be possible, right?
```
expected_output = {
    "indexes": {}
}
```
could you please add the output as unittest?

2021-09-04 01:51 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowCtsRoleBasedPermissions/cli/equal/sample_output_expected.py
> +        1: {
maybe some keyword from below and have key name for this info?
```
IPv4 Role-based permissions from group Invalid to group Invalid:
```

2021-09-04 01:51 UTC, tahigash commented on src/genie/libs/parser/iosxe/tests/ShowCtsRoleBasedPermissions/cli/equal/sample_output_expected.py
> +        "monitor_configured": False
even from parsed output, we could guess what they are. but I assume this name is very short. and doesn't tell this is for RBACL related. please consider updating schema with better key name.

2022-09-19 13:42 UTC, closed without merging