added spanning-tree portfast trunk to ShowRunInterface parser
CiscoTestAutomation/genieparser pull request #546
Opened 2021-09-24 00:37 UTC by smitsialis

## Description
Added a parser to ShowRunInterface for the following command:
 * spanning-tree portfast trunk
Also found variable in the schema that were duplicates.  Removed the duplicates.

## Motivation and Context
This was missing and is needed.

## Impact (If any)
no impact

## Screenshots:
![image](https://user-images.githubusercontent.com/42588542/134601085-61a01cb9-21b1-44cd-82ce-1185b5fd8289.png)

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2021-09-29 04:23 UTC, lsheikal commented on src/genie/libs/parser/iosxe/show_run.py
> -                Optional('spanning_tree_bpduguard'): str,
Why these keys have been removed from parser?

2021-09-29 04:23 UTC, lsheikal commented on src/genie/libs/parser/iosxe/show_run.py
> -                Optional('spanning_tree_portfast'): bool,
same. why its been removed?

2021-09-29 04:29 UTC, lsheikal requested changes

2021-09-29 04:29 UTC, lsheikal commented on changelog/undistributed/changelog_iosxe_ShowRunInterface_20210923201701.rst
> +--------------------------------------------------------------------------------
```suggestion
--------------------------------------------------------------------------------
                                  Fix
--------------------------------------------------------------------------------
* IOSXE
    * Modified ShowRunInterface:
        * Added new key spanning-tree portfast trunk
        * Removed duplicate keys spanning_tree_bpduguard and spanning_tree_portfast
```

2021-10-04 14:11 UTC, danielgraziano commented on src/genie/libs/parser/iosxe/show_run.py
> -                Optional('spanning_tree_bpduguard'): str,
they are duplicates

2021-10-04 14:11 UTC, danielgraziano commented on src/genie/libs/parser/iosxe/show_run.py
> -                Optional('spanning_tree_portfast'): bool,
they are duplicates

2021-10-04 14:13 UTC, danielgraziano requested changes
Please update the changelog

2021-10-04 14:13 UTC, danielgraziano commented on changelog/undistributed/changelog_iosxe_ShowRunInterface_20210923201701.rst
> +                * Optional('spanning_tree_portfast'): bool,
```suggestion
--------------------------------------------------------------------------------
                            New
--------------------------------------------------------------------------------
* IOSXE
    * Modified ShowRunInterface:
        * Added parsing support (schema and parsers) for following output
            * spanning-tree portfast trunk

--------------------------------------------------------------------------------
                            Fix
--------------------------------------------------------------------------------
* IOSXE
    * Modified ShowRunInterface:
        * Removed duplicate schema variables
                * Optional('spanning_tree_bpduguard'): str,
                * Optional('spanning_tree_portfast'): bool,
        * Added the following schema variable
                * Optional('spanning_tree_portfast_trunk'): bool,
```

2021-12-01 20:04 UTC, smitsialis commented
@danielgraziano  I had made the changes and re-submitted them before I saw there was a button to just approve.  I've re-requested a review.  Not sure where to go from here.  Let me know what I need to do.  Thanks,

2021-12-06 16:36 UTC, danielgraziano commented
@smitsialis Unfortunately you'll have to follow the below steps. We had to make some changes to the repository that are incompatible with any existing clones or forks.

First you'll have to save your parsers that you wrote and want to contribute.

Second, you'll need to delete your copy of the master (smitsialis:master) and then re-pull the master branch from the remote (CiscoTestAutomation:master). This step is required because the history had to be re-written :(.

Third, copy your saved parsers/tests back into your copy of master (smitsialis:master) and then create a pull request

2021-12-06 16:39 UTC, danielgraziano commented
Alternatively just save your changes, delete the fork, re-fork, copy your changes back in

2021-12-06 21:51 UTC, closed without merging