Release 21.9
CiscoTestAutomation/genieparser pull request #549
Opened 2021-09-29 23:51 UTC by GerriorL

## Description

## Motivation and Context

## Impact (If any)

## Screenshots:

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [ ] I have added tests to cover my changes (If applicable).
- [ ] All new and existing tests passed.
- [ ] All new code passed compilation.

2021-09-30 10:59 UTC, tahigash requested changes
`Files changed 1,929`. Is this correct?

2021-09-30 12:40 UTC, GerriorL commented
> `Files changed 1,929`. Is this correct?

Yes. This PR includes the migration from unittests to folder tests

2021-10-01 17:19 UTC, d-the-iii approved these changes
All the version bump information seems correct. The cicd changes seem fine. The json looks good. It looks like all the old test have been deleted. All the unit tests are passing. I don't think there's much more room for review with this pr than that.

2021-10-01 17:59 UTC, tahigash approved these changes

2021-10-01 18:00 UTC, merged