Added hsrp event history parsers (from PR #555)
CiscoTestAutomation/genieparser pull request #594
Opened 2021-12-14 13:53 UTC by divya883

## Description
Added parsers for the commands 'show hsrp internal event-history errors', 'show hsrp internal event-history msgs' and 'show hsrp internal event-history debugs' for nxos.

## Motivation and Context
I was working with hsrp as part of a project and wanted to retrieve related info and found that there were no parsers for the above commands.

## Impact (If any)
No negative impact expected.

## Screenshots:
show hsrp internal event-history errors

2021-12-14T19:09:08: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:09:08: %AETEST-INFO: |                       STEPS Report                       |
2021-12-14T19:09:08: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:09:08: %AETEST-INFO: STEP 1 - nxos -> ShowHsrpEventHistoryErrors           Passed
2021-12-14T19:09:08: %AETEST-INFO: STEP 1.1 - Test Golden -> nxos -> ShowHsrpEventHistoryErrors    Passed
2021-12-14T19:09:08: %AETEST-INFO: STEP 1.1.1 - Gold -> nxos -> ShowHsrpEventHistoryErrors -> golden_output1    Passed
2021-12-14T19:09:08: %AETEST-INFO: STEP 1.2 - Test Empty -> nxos -> ShowHsrpEventHistoryErrors    Passed
2021-12-14T19:09:08: %AETEST-INFO: STEP 1.2.1 - Empty -> nxos -> ShowHsrpEventHistoryErrors -> empty_output    Passed
2021-12-14T19:09:08: %AETEST-INFO: ------------------------------------------------------------

show hsrp internal event history msgs

2021-12-14T19:08:56: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:08:56: %AETEST-INFO: |                       STEPS Report                       |
2021-12-14T19:08:56: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:08:56: %AETEST-INFO: STEP 1 - nxos -> ShowHsrpEventHistoryMsgs             Passed
2021-12-14T19:08:56: %AETEST-INFO: STEP 1.1 - Test Golden -> nxos -> ShowHsrpEventHistoryMsgs    Passed
2021-12-14T19:08:56: %AETEST-INFO: STEP 1.1.1 - Gold -> nxos -> ShowHsrpEventHistoryMsgs -> golden_output1    Passed
2021-12-14T19:08:56: %AETEST-INFO: STEP 1.2 - Test Empty -> nxos -> ShowHsrpEventHistoryMsgs    Passed
2021-12-14T19:08:56: %AETEST-INFO: STEP 1.2.1 - Empty -> nxos -> ShowHsrpEventHistoryMsgs -> empty_output    Passed

show hsrp event history debugs

2021-12-14T19:09:20: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:09:20: %AETEST-INFO: |                       STEPS Report                       |
2021-12-14T19:09:20: %AETEST-INFO: +----------------------------------------------------------+
2021-12-14T19:09:20: %AETEST-INFO: STEP 1 - nxos -> ShowHsrpEventHistoryDebugs           Passed
2021-12-14T19:09:20: %AETEST-INFO: STEP 1.1 - Test Golden -> nxos -> ShowHsrpEventHistoryDebugs    Passed
2021-12-14T19:09:20: %AETEST-INFO: STEP 1.1.1 - Gold -> nxos -> ShowHsrpEventHistoryDebugs -> golden_output1    Passed
2021-12-14T19:09:20: %AETEST-INFO: STEP 1.2 - Test Empty -> nxos -> ShowHsrpEventHistoryDebugs    Passed
2021-12-14T19:09:20: %AETEST-INFO: STEP 1.2.1 - Empty -> nxos -> ShowHsrpEventHistoryDebugs -> empty_output    Passed
2021-12-14T19:09:20: %AETEST-INFO: ------------------------------------------------------------

## Checklist:
- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2021-12-17 20:32 UTC, LukasMcClelland requested changes
Thank you for opening up another PR with your contributions.

I caught an issue, but besides that it looks good

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +            out = self.device.execute(self.cli_command)
```suggestion
            output = self.device.execute(self.cli_command)
```

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +        for line in out.splitlines():
```suggestion
        for line in output.splitlines():
```

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +            out = self.device.execute(self.cli_command)
```suggestion
            output = self.device.execute(self.cli_command)
```

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +        for line in out.splitlines():
```suggestion
        for line in output.splitlines():
```

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +            out = self.device.execute(self.cli_command)
```suggestion
            output = self.device.execute(self.cli_command)
```

2021-12-17 20:32 UTC, LukasMcClelland commented on src/genie/libs/parser/nxos/show_hsrp_event_history.py
> +        for line in out.splitlines():
```suggestion
        for line in output.splitlines():
```

2021-12-20 21:53 UTC, lsheikal approved these changes

2022-03-29 13:43 UTC, LukasMcClelland approved these changes

2022-03-29 13:43 UTC, merged