'show tacacs' parser for IOSXR
CiscoTestAutomation/genieparser pull request #610
Opened 2022-02-03 15:32 UTC by PipeFTW

## Description
Parser for the command 'show tacacs' for IOSXR systems.

## Motivation and Context
The parser is needed in one of our projects

## Impact (If any)
-

## Screenshots:
-

## Checklist:
- [+ ] I have updated the changelog.
- [+ ] I have added tests to cover my changes (If applicable).
- [+] All new and existing tests passed.
- [+] All new code passed compilation.

2022-02-04 15:04 UTC, GerriorL requested changes
Hi there! Thank you for your submission. It looks great, but there are a couple of small changes I'd like to request.

2022-02-04 15:04 UTC, GerriorL commented on src/genie/libs/parser/iosxr/show_tacacs.py
> +            r'Server\:\s(?P<ip>[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]+)\svrf=(?P<vrf>[A-Za-z0-9]+)\s?\[(?P<server_type>\w+)\]')
Looks like these regex statements could be improved to make them more readable/flexible if this parser needs to be expanded in the future.

For example it's best to have them start and end with ^ and $ respectively, so they don't start or end reading anywhere but the beginning/end of the line.

In addition it's also best to use things like \d, \S, or \w in lieu of [0-9] or [a-zA-Z].

2022-02-04 15:04 UTC, GerriorL commented on src/genie/libs/parser/iosxr/show_tacacs.py
> +        serverdict = dict()
Using serverdict as the main dictionary, and resultdict as a subdictionary might be confusing; typically the main dictionary that gets returned is named ret_dict, but it's not a mandatory change in my opinion.

2022-02-04 15:04 UTC, GerriorL commented on src/genie/libs/parser/iosxr/show_tacacs.py
> +        serverdict = dict()
Typically it's preferred to use literal declaration when possible, {} instead of dict(), but again I think that's an optional change.

2022-02-07 14:14 UTC, GerriorL approved these changes
Great job on this parser! In the future you don't need to bother with the tests/show_tacacs.py file, just the folder based unittest is sufficient.

2022-02-07 14:16 UTC, PipeFTW commented
> Great job on this parser! In the future you don't need to bother with the tests/show_tacacs.py file, just the folder based unittest is sufficient.

Oh ok, I have another pull request open, have there a testfile too. Need to do 3-4 other command parser as well. Thanks for the info :)

2022-06-08 20:42 UTC, lsheikal approved these changes

2022-06-08 20:42 UTC, merged