Fix parser for show flow exporter statistics if exporter contains special character
CiscoTestAutomation/genieparser pull request #651
Opened 2022-04-07 15:52 UTC by ChristopherJHart

## Description
This PR fixes the issue reported in #648, where the parser for `show flow exporter statistics` fails if the name of the NetFlow exporter contains a special character.

## Motivation and Context
This change fixes a defect in the `show flow exporter statistics` parser.

## Impact (If any)
No negative impact is anticipated from this change.

## Screenshots:

All tests (existing and new) passing per output below.
```
2022-04-07T11:42:51: %GENIE-INFO: +------------------------------------------------------------------------------+
2022-04-07T11:42:51: %GENIE-INFO: |                                   Summary                                    |
2022-04-07T11:42:51: %GENIE-INFO: +------------------------------------------------------------------------------+
2022-04-07T11:42:51: %GENIE-INFO:  Number of ABORTED                                                            0
2022-04-07T11:42:51: %GENIE-INFO:  Number of BLOCKED                                                            0
2022-04-07T11:42:51: %GENIE-INFO:  Number of ERRORED                                                            0
2022-04-07T11:42:51: %GENIE-INFO:  Number of FAILED                                                             0
2022-04-07T11:42:51: %GENIE-INFO:  Number of PASSED                                                            19
2022-04-07T11:42:51: %GENIE-INFO:  Number of PASSX                                                              0
2022-04-07T11:42:51: %GENIE-INFO:  Number of SKIPPED                                                            0
2022-04-07T11:42:51: %GENIE-INFO:  Total Number                                                                19
2022-04-07T11:42:51: %GENIE-INFO:  Success Rate                                                            100.0%
2022-04-07T11:42:51: %GENIE-INFO: --------------------------------------------------------------------------------
2022-04-07T11:42:51: %GENIE-INFO:  Total Parsers Missing Unittests                                            255
2022-04-07T11:42:51: %GENIE-INFO: --------------------------------------------------------------------------------
2022-04-07T11:42:51: %GENIE-INFO:  Total Passing Unittests                                                   5829
2022-04-07T11:42:51: %GENIE-INFO:  Total Failed Unittests                                                       0
2022-04-07T11:42:51: %GENIE-INFO:  Total Errored Unittests                                                      0
2022-04-07T11:42:51: %GENIE-INFO:  Total Unittests                                                           5829
2022-04-07T11:42:51: %GENIE-INFO: --------------------------------------------------------------------------------
```

## Checklist:

- [x] I have updated the changelog.
- [x] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

2022-04-08 13:51 UTC, GerriorL requested changes
Everything looks great here, but we're just missing a changelog. 
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/contribute/contribute.html#update-the-changelog

2022-04-08 19:17 UTC, GerriorL approved these changes

2022-04-14 03:41 UTC, LukasMcClelland approved these changes

2022-04-14 03:41 UTC, merged

2022-04-14 03:41 UTC, LukasMcClelland commented
Thank you for contributing!