Added ShowInterfacesCapabities, fixed ShowRunInterface, fixed ShowSwi…
CiscoTestAutomation/genieparser pull request #678
Opened 2022-06-20 20:52 UTC by smitsialis

…tchStackPortSummary

## Description
- Added Show Interfaces Capabilities
- Fixed Show Switch StackPort Summary to support interfaces with the slash notation
- Modified Show Run interfaces to include speed and duplex parsing

## Motivation and Context
- Show Interfaces Capabilities is a new parser
- Show Switch StackPort summary was only working for certain models.   This now works for other models that have a slash in the interface name
- Added missing speed and duplex parsing to Show run interfaces

## Impact (If any)
None

## Screenshots:
![image](https://user-images.githubusercontent.com/42588542/174676084-eabb3b99-df79-4f60-ad45-2a5b43cc3409.png)

![image](https://user-images.githubusercontent.com/42588542/174676151-95c2504e-dbd2-4f36-aa1b-32e34d352fd6.png)

![image](https://user-images.githubusercontent.com/42588542/174676231-6778f27b-de0f-4c50-8462-f264b8a75cfc.png)

## Checklist:

- [ x ] I have updated the changelog.
- [  ] I have updated the documentation (If applicable).
- [ x ] I have added tests to cover my changes (If applicable).
- [ x ] All new and existing tests passed.
- [ x  ] All new code passed compilation.

2022-07-05 18:22 UTC, ademz commented
Hello @smitsialis ,

Thank you for your contribution. Can you please merge the latest version and fix the conflicts? 

Adem Oztas

2022-07-25 14:38 UTC, stevedhn commented
Hi pls resolve the conflicts by merging with the lastest dev branch

2022-08-09 18:27 UTC, GerriorL reviewed
Code looks good, just one small change to the changelog

2022-08-09 18:27 UTC, GerriorL commented on changelog/undistributed/changelog_multiple.rst
> +        * show interfaces {interface} capabilities
Please separate IOS and IOSXE

2022-08-11 14:01 UTC, GerriorL requested changes
Unfortunately we can't make schema changes as we need to preserve backwards compatibility

2022-12-15 16:06 UTC, closed without merging