Changed regex p16_1 in IOSXE show version to cover license type names…
CiscoTestAutomation/genieparser pull request #686
Opened 2022-07-25 14:27 UTC by dirkf98

… with spaces

## Description
Changed regex p16_1 in IOSXE show version. Tests for golden_output 9 have been added to cover the changes.

## Motivation and Context
The original parser fails because the license type on my 4507R+E contains whitespaces that are not covered in the regex.

## Impact (If any)
None

## Screenshots:
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: |                   Starting testcase SuperFileBasedTesting                    |
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: |                            Starting section setup                            |
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: The result of section setup is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: The result of testcase SuperFileBasedTesting is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: |                           Starting testcase iosxe                            |
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: |                            Starting section setup                            |
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: The result of section setup is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: |                         Starting section ShowVersion                         |
2022-07-25T16:21:54: %AETEST-INFO: +------------------------------------------------------------------------------+
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :                    Starting STEP 1: iosxe -> ShowVersion                     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :            Starting STEP 1.1: Test Golden -> iosxe -> ShowVersion            :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.1: Gold -> iosxe -> ShowVersion -> golden_output_1     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.1: Gold -> iosxe -> ShowVersion -> golden_output_1 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.2: Gold -> iosxe -> ShowVersion -> golden_output_2     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.2: Gold -> iosxe -> ShowVersion -> golden_output_2 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.3: Gold -> iosxe -> ShowVersion -> golden_output_3     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.3: Gold -> iosxe -> ShowVersion -> golden_output_3 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.4: Gold -> iosxe -> ShowVersion -> golden_output_4     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.4: Gold -> iosxe -> ShowVersion -> golden_output_4 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.5: Gold -> iosxe -> ShowVersion -> golden_output_5     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.5: Gold -> iosxe -> ShowVersion -> golden_output_5 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.6: Gold -> iosxe -> ShowVersion -> golden_output_6     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.6: Gold -> iosxe -> ShowVersion -> golden_output_6 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.7: Gold -> iosxe -> ShowVersion -> golden_output_7     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.7: Gold -> iosxe -> ShowVersion -> golden_output_7 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.8: Gold -> iosxe -> ShowVersion -> golden_output_8     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.8: Gold -> iosxe -> ShowVersion -> golden_output_8 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :     Starting STEP 1.1.9: Gold -> iosxe -> ShowVersion -> golden_output_9     :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.9: Gold -> iosxe -> ShowVersion -> golden_output_9 is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :    Starting STEP 1.1.10: Gold -> iosxe -> ShowVersion -> golden_output_95    :
2022-07-25T16:21:54: %AETEST-INFO: :                                00h_standalone                                :
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: The result of STEP 1.1.10: Gold -> iosxe -> ShowVersion -> golden_output_9500h_standalone is => PASSED
2022-07-25T16:21:54: %AETEST-INFO: +..............................................................................+
2022-07-25T16:21:54: %AETEST-INFO: :    Star [...]

2022-07-25 20:09 UTC, Taarini requested changes

2022-07-25 20:09 UTC, Taarini commented on src/genie/libs/parser/iosxe/show_platform.py
>          # entservices   Type: Permanent
Please add the comment like below
```suggestion
        # entservices   Type: Permanent
        # License Level: entservices   Type: Permanent Right-To-Use
```

2022-07-26 19:47 UTC, Taarini approved these changes

2022-07-26 19:47 UTC, Taarini commented on src/genie/libs/parser/iosxe/show_platform.py
> +        # License Level: entservices   Type: Permanent Right-To-Use
You don't have to repeat if it is same comment

2022-08-11 13:51 UTC, GerriorL approved these changes

2022-08-11 14:02 UTC, merged